version: '3.5'

networks:
  nat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 178.80.0.0/16

services:
  gateway.api:
    image: gatewayapi_image
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    expose:
      - "80"
    ports:
      - "7000:80"
    networks:
      nat:
        ipv4_address: 178.80.0.2
    links:
      - catalog.api
      - orders.api
    depends_on:
      - catalog.api
      - orders.api
  
  catalog.api:
    image: catalogapi_image
    build:
      context: .
      dockerfile: CatalogApi/Dockerfile
    expose:
      - "80"
    ports:
      - "7001:80"
    networks:
      nat:
        ipv4_address: 178.80.0.3
  
  orders.api:
    image: ordersapi_image
    build:
      context: .
      dockerfile: OrdersApi/Dockerfile
    expose:
      - "80"
    ports:
      - "7002:80"
    networks:
      nat:
        ipv4_address: 178.80.0.4
